export const MAJOR = {
  COMPUTER_SCIENCE: 'COMPUTER_SCIENCE',
  SOFTWARE_ENGINEERING: 'SOFTWARE_ENGINEERING',
  INFORMATION_SECURITY: 'INFORMATION_SECURITY',
  DATA_SCIENCE: 'DATA_SCIENCE',
  ELECTRICAL_ENGINEERING: 'ELECTRICAL_ENGINEERING',
  MECHANICAL_ENGINEERING: 'MECHANICAL_ENGINEERING',
  BUSINESS_ADMINISTRATION: 'BUSINESS_ADMINISTRATION',
  ECONOMICS: 'ECONOMICS',
  DESIGN: 'DESIGN',
  OTHER: 'OTHER'
};

export const MAJOR_LABELS = {
  [MAJOR.COMPUTER_SCIENCE]: '컴퓨터공학',
  [MAJOR.SOFTWARE_ENGINEERING]: '소프트웨어공학',
  [MAJOR.INFORMATION_SECURITY]: '정보보안',
  [MAJOR.DATA_SCIENCE]: '데이터사이언스',
  [MAJOR.ELECTRICAL_ENGINEERING]: '전기공학',
  [MAJOR.MECHANICAL_ENGINEERING]: '기계공학',
  [MAJOR.BUSINESS_ADMINISTRATION]: '경영학',
  [MAJOR.ECONOMICS]: '경제학',
  [MAJOR.DESIGN]: '디자인',
  [MAJOR.OTHER]: '기타'
};

export const JOB_CATEGORY = {
  BACKEND_DEVELOPER: 'BACKEND_DEVELOPER',
  FRONTEND_DEVELOPER: 'FRONTEND_DEVELOPER',
  MOBILE_DEVELOPER: 'MOBILE_DEVELOPER',
  DATA_ENGINEER: 'DATA_ENGINEER',
  AI_ML_ENGINEER: 'AI_ML_ENGINEER',
  PRODUCT_MANAGER: 'PRODUCT_MANAGER',
  DESIGNER: 'DESIGNER',
  MARKETER: 'MARKETER',
  OTHER: 'OTHER'
};

export const JOB_LABELS = {
  [JOB_CATEGORY.BACKEND_DEVELOPER]: '백엔드 개발자',
  [JOB_CATEGORY.FRONTEND_DEVELOPER]: '프론트엔드 개발자',
  [JOB_CATEGORY.MOBILE_DEVELOPER]: '모바일 개발자',
  [JOB_CATEGORY.DATA_ENGINEER]: '데이터 엔지니어',
  [JOB_CATEGORY.AI_ML_ENGINEER]: 'AI/ML 엔지니어',
  [JOB_CATEGORY.PRODUCT_MANAGER]: 'PM/PO',
  [JOB_CATEGORY.DESIGNER]: '디자이너',
  [JOB_CATEGORY.MARKETER]: '마케터',
  [JOB_CATEGORY.OTHER]: '기타'
};

export const COUNTRY = {
  KOREA: 'KOREA',
  USA: 'USA',
  JAPAN: 'JAPAN',
  CHINA: 'CHINA',
  GERMANY: 'GERMANY',
  UK: 'UK',
  CANADA: 'CANADA',
  OTHER: 'OTHER'
};

export const COUNTRY_LABELS = {
  [COUNTRY.KOREA]: '한국',
  [COUNTRY.USA]: '미국',
  [COUNTRY.JAPAN]: '일본',
  [COUNTRY.CHINA]: '중국',
  [COUNTRY.GERMANY]: '독일',
  [COUNTRY.UK]: '영국',
  [COUNTRY.CANADA]: '캐나다',
  [COUNTRY.OTHER]: '기타'
};

export const POST_CATEGORY = {
  FREE: 'FREE',
  JOB: 'JOB',
  QA: 'QA',
  PROFESSOR_NOTICE: 'PROFESSOR_NOTICE'
};

export const POST_CATEGORY_LABELS = {
  [POST_CATEGORY.FREE]: '자유게시판',
  [POST_CATEGORY.JOB]: '취업/진로',
  [POST_CATEGORY.QA]: '질문답변',
  [POST_CATEGORY.PROFESSOR_NOTICE]: '공지사항'
};
